"""Enumerations required by TRIDENT implementation directive 100B."""

from enum import StrEnum


class ProjectMemberRole(StrEnum):
    """Project-scoped RBAC (TRIDENT_IMPLEMENTATION_DIRECTIVE_001)."""

    OWNER = "OWNER"
    ADMIN = "ADMIN"
    CONTRIBUTOR = "CONTRIBUTOR"
    VIEWER = "VIEWER"


class TaskLifecycleState(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    # Blueprint / APP_LLD task-ledger vocabulary (STATE_001 — additive)
    PROOF_RETURNED = "PROOF_RETURNED"
    BUG_CHECKING = "BUG_CHECKING"
    SIGNED_OFF = "SIGNED_OFF"


class AgentRole(StrEnum):
    ARCHITECT = "ARCHITECT"
    ENGINEER = "ENGINEER"
    REVIEWER = "REVIEWER"
    DOCUMENTATION = "DOCUMENTATION"
    DEBUGGER = "DEBUGGER"
    SYSTEM = "SYSTEM"
    USER = "USER"


class DirectiveStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"
    # Blueprint lifecycle (STATE_001 — additive; existing values unchanged)
    ISSUED = "ISSUED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PLANNING = "PLANNING"
    PLAN_ACCEPTED = "PLAN_ACCEPTED"
    BUILDING = "BUILDING"
    PROOF_RETURNED = "PROOF_RETURNED"
    PROOF_ACCEPTED = "PROOF_ACCEPTED"
    BUG_CHECKING = "BUG_CHECKING"
    SIGNED_OFF = "SIGNED_OFF"
    NEXT_ISSUED = "NEXT_ISSUED"
    BLOCKED = "BLOCKED"
    # SIGNOFF_001 — governed closure
    CLOSED = "CLOSED"


class ProofObjectType(StrEnum):
    GIT_DIFF = "GIT_DIFF"
    TEST_OUTPUT = "TEST_OUTPUT"
    EXECUTION_LOG = "EXECUTION_LOG"
    CHAT_LOG = "CHAT_LOG"
    SCREENSHOT = "SCREENSHOT"
    COMMIT_HASH = "COMMIT_HASH"
    DOCUMENTATION_UPDATE = "DOCUMENTATION_UPDATE"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    PERFORMANCE_REPORT = "PERFORMANCE_REPORT"
    BACKUP_RESTORE_PROOF = "BACKUP_RESTORE_PROOF"
    OTHER = "OTHER"
    # GITHUB_002 — git provider proof types
    GIT_BRANCH_CREATED = "GIT_BRANCH_CREATED"
    GIT_COMMIT_PUSHED = "GIT_COMMIT_PUSHED"
    # VALIDATION_001 — proof types for validation outcome
    VALIDATION_RUN_PASSED = "VALIDATION_RUN_PASSED"
    VALIDATION_RUN_FAILED = "VALIDATION_RUN_FAILED"
    # SIGNOFF_001
    DIRECTIVE_SIGNOFF = "DIRECTIVE_SIGNOFF"


class AuditEventType(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    AUTH_REFRESH = "AUTH_REFRESH"
    PROJECT_CREATED = "PROJECT_CREATED"
    MEMBER_INVITED = "MEMBER_INVITED"
    MEMBER_ACCEPTED = "MEMBER_ACCEPTED"
    CONTROL_PLANE_ACTION = "CONTROL_PLANE_ACTION"
    ONBOARDING_STARTED = "ONBOARDING_STARTED"
    ONBOARDING_SCAN_COMPLETE = "ONBOARDING_SCAN_COMPLETE"
    ONBOARDING_INDEX_QUEUED = "ONBOARDING_INDEX_QUEUED"
    ONBOARDING_APPROVED = "ONBOARDING_APPROVED"
    ONBOARDING_REJECTED = "ONBOARDING_REJECTED"
    DIRECTIVE_CREATED = "DIRECTIVE_CREATED"
    MEMORY_WRITE = "MEMORY_WRITE"
    MEMORY_VECTOR_INDEX_FAILED = "MEMORY_VECTOR_INDEX_FAILED"
    MEMORY_VECTOR_REINDEX_SUCCESS = "MEMORY_VECTOR_REINDEX_SUCCESS"
    MEMORY_READ_ACCESS = "MEMORY_READ_ACCESS"
    STATE_TRANSITION = "STATE_TRANSITION"
    GRAPH_STATE_WRITTEN = "GRAPH_STATE_WRITTEN"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_ACKNOWLEDGED = "HANDOFF_ACKNOWLEDGED"
    PROOF_ATTACHED = "PROOF_ATTACHED"
    LOCK_CREATED = "LOCK_CREATED"
    LOCK_REJECTED = "LOCK_REJECTED"
    LOCK_RELEASED = "LOCK_RELEASED"
    LOCK_HEARTBEAT = "LOCK_HEARTBEAT"
    LOCK_STALE = "LOCK_STALE"
    LOCK_RECOVERED = "LOCK_RECOVERED"
    LOCK_TAKEOVER = "LOCK_TAKEOVER"
    LOCK_FORCE_RELEASED = "LOCK_FORCE_RELEASED"
    GIT_STATUS_CHECKED = "GIT_STATUS_CHECKED"
    DIFF_GENERATED = "DIFF_GENERATED"
    ROUTER_DECISION = "ROUTER_DECISION"
    ROUTER_DECISION_MADE = "ROUTER_DECISION_MADE"
    MCP_EXECUTION_REQUESTED = "MCP_EXECUTION_REQUESTED"
    MCP_EXECUTION_COMPLETED = "MCP_EXECUTION_COMPLETED"
    MCP_EXECUTION_REJECTED = "MCP_EXECUTION_REJECTED"
    MCP_EXECUTION_FAILED = "MCP_EXECUTION_FAILED"
    AGENT_INVOCATION = "AGENT_INVOCATION"
    AGENT_DECISION = "AGENT_DECISION"
    AGENT_MCP_REQUEST = "AGENT_MCP_REQUEST"
    AGENT_RESULT = "AGENT_RESULT"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    IDE_CHAT_REQUEST = "IDE_CHAT_REQUEST"
    IDE_CHAT_RESPONSE = "IDE_CHAT_RESPONSE"
    IDE_ORCHESTRATED_ACTION = "IDE_ORCHESTRATED_ACTION"
    PATCH_PROPOSED = "PATCH_PROPOSED"
    PATCH_REJECTED = "PATCH_REJECTED"
    PATCH_APPLIED = "PATCH_APPLIED"
    PATCH_ACCEPTED = "PATCH_ACCEPTED"
    PATCH_EXECUTED = "PATCH_EXECUTED"
    PATCH_EXECUTION_FAILED = "PATCH_EXECUTION_FAILED"
    # VALIDATION_001
    VALIDATION_CREATED = "VALIDATION_CREATED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_WAIVED = "VALIDATION_WAIVED"
    # SIGNOFF_001
    SIGNOFF_COMPLETED = "SIGNOFF_COMPLETED"
    # AGENT_RUNTIME_001
    AGENT_RUN_STARTED = "AGENT_RUN_STARTED"
    AGENT_RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    AGENT_RUN_FAILED = "AGENT_RUN_FAILED"
    # AGENT_REVIEWER_001
    AGENT_REVIEW_STARTED = "AGENT_REVIEW_STARTED"
    AGENT_REVIEW_COMPLETED = "AGENT_REVIEW_COMPLETED"
    AGENT_REVIEW_FAILED = "AGENT_REVIEW_FAILED"
    # DECISION_ENGINE_001
    DECISION_RECORDED = "DECISION_RECORDED"
    MODEL_ROUTING_DECISION = "MODEL_ROUTING_DECISION"
    MODEL_ROUTING_BUDGET_WARNING = "MODEL_ROUTING_BUDGET_WARNING"
    MODEL_ROUTER_BENCHMARK = "MODEL_ROUTER_BENCHMARK"
    # GITHUB_002 — git provider audit events
    GIT_REPO_CREATED = "GIT_REPO_CREATED"
    GIT_REPO_LINKED = "GIT_REPO_LINKED"
    GIT_BRANCH_CREATED = "GIT_BRANCH_CREATED"
    GIT_COMMIT_PUSHED = "GIT_COMMIT_PUSHED"
    # GITHUB_004 — directive-lifecycle git events
    GIT_BRANCH_CREATE_FAILED = "GIT_BRANCH_CREATE_FAILED"


class AuditActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
