"""Enumerations required by TRIDENT implementation directive 100B."""

from enum import StrEnum


class TaskLifecycleState(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class AgentRole(StrEnum):
    ARCHITECT = "ARCHITECT"
    ENGINEER = "ENGINEER"
    REVIEWER = "REVIEWER"
    DOCUMENTATION = "DOCUMENTATION"
    SYSTEM = "SYSTEM"
    USER = "USER"


class DirectiveStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"


class ProofObjectType(StrEnum):
    GIT_DIFF = "GIT_DIFF"
    TEST_OUTPUT = "TEST_OUTPUT"
    EXECUTION_LOG = "EXECUTION_LOG"
    SCREENSHOT = "SCREENSHOT"
    COMMIT_HASH = "COMMIT_HASH"
    DOCUMENTATION_UPDATE = "DOCUMENTATION_UPDATE"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    PERFORMANCE_REPORT = "PERFORMANCE_REPORT"
    BACKUP_RESTORE_PROOF = "BACKUP_RESTORE_PROOF"
    OTHER = "OTHER"


class AuditEventType(StrEnum):
    DIRECTIVE_CREATED = "DIRECTIVE_CREATED"
    MEMORY_WRITE = "MEMORY_WRITE"
    MEMORY_VECTOR_INDEX_FAILED = "MEMORY_VECTOR_INDEX_FAILED"
    MEMORY_VECTOR_REINDEX_SUCCESS = "MEMORY_VECTOR_REINDEX_SUCCESS"
    MEMORY_READ_ACCESS = "MEMORY_READ_ACCESS"
    STATE_TRANSITION = "STATE_TRANSITION"
    GRAPH_STATE_WRITTEN = "GRAPH_STATE_WRITTEN"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_ACKNOWLEDGED = "HANDOFF_ACKNOWLEDGED"
    PROOF_ATTACHED = "PROOF_ATTACHED"
    LOCK_CREATED = "LOCK_CREATED"
    LOCK_REJECTED = "LOCK_REJECTED"
    LOCK_RELEASED = "LOCK_RELEASED"
    GIT_STATUS_CHECKED = "GIT_STATUS_CHECKED"
    DIFF_GENERATED = "DIFF_GENERATED"
    ROUTER_DECISION = "ROUTER_DECISION"
    MCP_EXECUTION_REQUESTED = "MCP_EXECUTION_REQUESTED"
    MCP_EXECUTION_COMPLETED = "MCP_EXECUTION_COMPLETED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class AuditActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
